on:
  pull_request:
  push:
    branches: [pure-c-port]
name: "c-asan"
jobs:
  build:
    name: AddressSanitizer on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build and run with ASAN
        run: |
          cd core
          make asan
