on:
  push:
  pull_request:
name: "c-tests"
jobs:
  build:
    name: Testing on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-2022
          - os: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Load .env file
        uses: xom9ikk/dotenv@v2
        with:
          path: ./
          load-mode: strict

      - name: Rust Nightly
        run: |
          rustup toolchain install nightly
          rustup update

      - name: Windows rust toolchain
        if: runner.os == 'Windows'
        run: |
          rustup toolchain install nightly-x86_64-pc-windows-gnu
          rustup component add rust-src --toolchain nightly-x86_64-pc-windows-gnu
          rustup default nightly-x86_64-pc-windows-gnu

      - name: Test
        run: |
          cd core
          make test
