on:
  pull_request:
  push:
    branches: [pure-c-port]
name: "c-tests"
jobs:
  build:
    name: Testing on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build and test
        run: |
          cd core
          cmake -B build -DCMAKE_BUILD_TYPE=Debug
          cmake --build build
          cd build && ctest --output-on-failure
