on:
  pull_request:
  push:
    branches: [pure-c-port]
name: "c-valgrind"
jobs:
  build:
    name: Valgrind
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install valgrind
        run: sudo apt update && sudo apt install -y valgrind

      - name: Build
        run: |
          cd core
          cmake -B build -DCMAKE_BUILD_TYPE=Debug
          cmake --build build

      - name: Run under valgrind
        run: |
          cd core/build
          valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes --error-exitcode=1 -s ./crsqlite_test
