on:
  pull_request:
  push:
    branches: [pure-c-port]
name: "c-valgrind"
jobs:
  build:
    name: Valgrind on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install valgrind
        run: sudo apt update && sudo apt install -y valgrind

      - name: Build tests
        run: |
          cd core
          make test

      - name: Run under valgrind
        run: |
          cd core
          valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes --error-exitcode=1 -s dist/test
