on:
  pull_request:
  push:
    branches: [pure-c-port]
name: "py-tests"
jobs:
  build:
    name: Testing on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build loadable extension
        run: |
          cd core
          make loadable

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: true
          activate-environment: ""
          python-version: "3.12"

      - name: Install SQLite with extension support
        run: conda install -y sqlite

      - name: Install test dependencies
        run: |
          pip install pytest hypothesis
          cd py/correctness && pip install -e .

      - name: Test
        run: |
          cd py/correctness
          pytest -v
