on:
  push:
  pull_request:
name: "py-tests"
jobs:
  build:
    name: Testing on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-2022
          - os: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Load .env file
        uses: xom9ikk/dotenv@v2
        with:
          path: ./
          load-mode: strict

      - name: Rust Nightly
        run: |
          rustup toolchain install nightly
          rustup update

      - name: Windows rust toolchain
        if: runner.os == 'Windows'
        run: |
          rustup target add x86_64-pc-windows-gnu
          rustup toolchain install nightly-x86_64-pc-windows-gnu
          rustup component add rust-src --toolchain nightly-x86_64-pc-windows-gnu

      - name: Make loadable
        run: |
          cd core
          make loadable

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: true
          activate-environment: anaconda-client-env
          python-version: "3.10"

      - name: Install SQLite
        run: conda install sqlite

      - name: Check SQLite Version
        run: echo "import sqlite3; print(sqlite3.sqlite_version)" | python

      # - name: Install Python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: "3.10"

      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Pip Deps
        run: cd py/correctness && pip install -e .

      - name: Test
        run: cd py/correctness && pytest
